# Generated by Django 4.2.3 on 2023-07-29 12:47

from django.db import migrations
import users.services


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.services.UserCManager()),
            ],
        ),
    ]
